apiVersion: batch/v1
kind: Job
metadata:
  name: init-job
spec:
  template:
    spec:
      restartPolicy: Never
      volumes:
        - name: dash-init-scripts
          configMap:
            name: dash-init-script
            defaultMode: 0755
        - name: dash-account-secrets
          secret:
            secretName: dash-account-secrets
      containers:
        - name: init-script
          image: curlimages/curl:8.5.0
          # directly invoke the script (it has a shebang and the execute bit)
          command:
            - /scripts/init-job.sh
          volumeMounts:
            - name: dash-init-scripts
              mountPath: /scripts
              readOnly: true
            - name: dash-account-secrets
              mountPath: /secrets
              readOnly: true
  backoffLimit: 3
