version: 2.1

jobs:
  build-backend:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Docker login to ACR
          command: |
            docker login -u $ACR_USERNAME -p $ACR_PASSWORD $ACR_URL
      - run:
          name: Build & push BE
          command: |
            docker buildx build --platform=linux/amd64 --no-cache \
              -t $ACR_URL/$ACR_USERNAME/dash-be:v0.0.3 \
              ./dash-be --push

  build-frontend:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Docker login to ACR
          command: |
            docker login -u $ACR_USERNAME -p $ACR_PASSWORD $ACR_URL
      - run:
          name: Build & push FE
          command: |
            docker buildx build --platform=linux/amd64 --no-cache \
              --build-arg REACT_APP_API_BASE_URL=/api \
              -t $ACR_URL/$ACR_USERNAME/dash-fe:v0.0.3 \
              ./dash-fe --push

workflows:
  build-and-push:
    jobs:
      - build-backend:
          context: [registry]
      - build-frontend:
          requires: [build-backend]
          context: [registry]
