version: 2.1

jobs:
  build-backend:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Docker login to ACR
          command: |
            docker login -u $ACR_USERNAME -p $ACR_PASSWORD $ACR_URL
      - run:
          name: Build & push BE
          command: |
            VERSION=$(cat VERSION)
            if [ "${CIRCLE_BRANCH}" = "main" ]; then
              DATE=$(date +'%d%m')
              TAG="be-${VERSION}-${DATE}"
            else
              TAG="be-${VERSION}"
            fi
            docker buildx build --platform=linux/amd64 --no-cache \
              -t $ACR_URL/$ACR_USERNAME/dash-be:$TAG \
              --push ./dash-be

  build-frontend:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Docker login to ACR
          command: |
            docker login -u $ACR_USERNAME -p $ACR_PASSWORD $ACR_URL
      - run:
          name: Build & push FE
          command: |
            VERSION=$(cat VERSION)
            if [ "${CIRCLE_BRANCH}" = "main" ]; then
              DATE=$(date +'%d%m')
              TAG="fe-${VERSION}-${DATE}"
            else
              TAG="fe-${VERSION}"
            fi
            echo "export TAG=$TAG" >> $BASH_ENV
            docker buildx build --platform=linux/amd64 --no-cache \
              --build-arg REACT_APP_API_BASE_URL=/api \
              -t $ACR_URL/$ACR_USERNAME/dash-fe:$TAG \
              --push ./dash-fe

workflows:
  dev-push:
    jobs:
      - build-backend:
          context: [registry]
          filters:
            branches:
              only: dev
      - build-frontend:
          requires: [build-backend]
          context: [registry]
          filters:
            branches:
              only: dev
  
  prod-push:
    jobs:
      - build-backend:
          context: [registry]
          filters:
            branches:
              only: main
      - build-frontend:
          context: [ registry ]
          requires: [ build-backend ]
          filters:
            branches:
              only: main
